# Generated by Django 3.2.6 on 2022-01-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('security_question', models.CharField(max_length=100)),
                ('question_answer', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(blank=True, upload_to='Profile_Image')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
